format:
  line_width: 120
  tab_size: 4
  dangle_parens: true

lint:
  function_pattern: "[0-9a-z_]+"
  macro_pattern: "[0-9a-z_]+"
  global_var_pattern: "[a-z][0-9a-z_]+"
  internal_var_pattern: "_[a-z][0-9a-z_]+"
  local_var_pattern: "[a-zA-Z_][a-zA-Z0-9_]+"
  private_var_pattern: "_[0-9a-z_]+"
  public_var_pattern: "[a-zA-Z][0-9a-zA-Z_]+"
  argument_var_pattern: "[a-z][a-z0-9_]+"
  keyword_pattern: "[a-z][0-9a-z_]+"
